version: "3.8"

volumes:
  vscode-extensions:
    external: true
  thunder-client:
    external: true

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME:-supabase}-net

services:
  vscode:
    init: true
    build:
      context: ..
      args:
        - VARIANT=${NODE_VERSION:-16}-${OS_VERSION:-bullseye}
        - FLAVOUR=${BASE_LANGUAGE:-typescript}
      dockerfile: .devcontainer/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-supabase}-vscode
    command: sleep infinity
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
    networks:
      - default
    volumes:
      - ..:/supabase
      - ~/.ssh:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
      - vscode-extensions:/root/.vscode-server/extensions
      - thunder-client:/root/.vscode-server/data/User/globalStorage/rangav.vscode-thunder-client
